WITH RENTABLE_CARS AS (
  SELECT CAR_ID, CAR_TYPE
  FROM CAR_RENTAL_COMPANY_CAR
  WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
),
DISCOUNTED_FEE AS (
  SELECT
    RENTABLE_CARS.CAR_ID,
    RENTABLE_CARS.CAR_TYPE,
    CASE
      WHEN DISCOUNT_RATE IS NOT NULL THEN FLOOR(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100)
      ELSE DAILY_FEE * 30
    END AS FEE
  FROM RENTABLE_CARS
  JOIN CAR_RENTAL_COMPANY_CAR ON RENTABLE_CARS.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    ON RENTABLE_CARS.CAR_TYPE = CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE
      AND CAR_RENTAL_COMPANY_DISCOUNT_PLAN.DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM DISCOUNTED_FEE
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;