SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
  SELECT 
    FOOD_TYPE, 
    REST_ID, 
    REST_NAME, 
    FAVORITES,
    RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
  FROM REST_INFO
  WHERE FOOD_TYPE IS NOT NULL
) a
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC;