-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS 'YEAR', MONTH(o.SALES_DATE) AS 'MONTH', GENDER, COUNT(DISTINCT i.USER_ID) AS 'USERS'
FROM USER_INFO i
JOIN ONLINE_SALE o ON i.USER_ID = o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), GENDER
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), GENDER
