SELECT CAR_ID,
       CASE WHEN EXISTS (
                 SELECT 1
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE CAR_ID = CRC.CAR_ID
                   AND '2022-10-16' BETWEEN START_DATE AND END_DATE
             ) THEN '대여중'
            ELSE '대여 가능'
       END AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) CRC
ORDER BY CAR_ID DESC;