SELECT GB.TITLE,
        GB.BOARD_ID,
        GR.REPLY_ID, 
        GR.WRITER_ID, 
        GR.CONTENTS, 
        DATE_FORMAT(GR.CREATED_DATE, "%Y-%m-%d") as 'CREATED_DATE'
FROM USED_GOODS_BOARD GB
JOIN USED_GOODS_REPLY GR ON GB.BOARD_ID = GR.BOARD_ID
WHERE GB.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY GR.CREATED_DATE ASC, GB.TITLE ASC